class ICountryWithCodeAndDial {
  final String countryName;
  final String countryCode;
  final String dialCode;

  ICountryWithCodeAndDial({this.countryName, this.countryCode, this.dialCode});
}

class CountryNameWithCodeAndDialCode {
  List<ICountryWithCodeAndDial> getArray() {
    return [
      ICountryWithCodeAndDial(countryName: 'ANDORRA', countryCode: 'ad', dialCode: '376'),
      ICountryWithCodeAndDial(countryName: 'UNITED ARAB EMIRATES', countryCode: 'ae', dialCode: '971'),
      ICountryWithCodeAndDial(countryName: 'AFGHANISTAN', countryCode: 'af', dialCode: '93'),
      ICountryWithCodeAndDial(countryName: 'ANTIGUA AND BARBUDA', countryCode: 'ag', dialCode: '1268'),
      ICountryWithCodeAndDial(countryName: 'ANGUILLA', countryCode: 'ai', dialCode: '1264'),
      ICountryWithCodeAndDial(countryName: 'ALBANIA', countryCode: 'al', dialCode: '355'),
      ICountryWithCodeAndDial(countryName: 'ARMENIA', countryCode: 'am', dialCode: '374'),
      ICountryWithCodeAndDial(countryName: 'NETHERLANDS ANTILLES', countryCode: 'an', dialCode: '599'),
      ICountryWithCodeAndDial(countryName: 'ANGOLA', countryCode: 'ao', dialCode: '244'),
      ICountryWithCodeAndDial(countryName: 'ANTARCTICA', countryCode: 'aq', dialCode: '672'),
      ICountryWithCodeAndDial(countryName: 'ARGENTINA', countryCode: 'ar', dialCode: '54'),
      ICountryWithCodeAndDial(countryName: 'AMERICAN SAMOA', countryCode: 'as', dialCode: '1684'),
      ICountryWithCodeAndDial(countryName: 'AUSTRIA', countryCode: 'at', dialCode: '43'),
      ICountryWithCodeAndDial(countryName: 'AUSTRALIA', countryCode: 'au', dialCode: '61'),
      ICountryWithCodeAndDial(countryName: 'ARUBA', countryCode: 'aw', dialCode: '297'),
      ICountryWithCodeAndDial(countryName: 'AZERBAIJAN', countryCode: 'az', dialCode: '994'),
      ICountryWithCodeAndDial(countryName: 'BOSNIA AND HERZEGOVINA', countryCode: 'ba', dialCode: '387'),
      ICountryWithCodeAndDial(countryName: 'BARBADOS', countryCode: 'bb', dialCode: '1246'),
      ICountryWithCodeAndDial(countryName: 'BANGLADESH', countryCode: 'bd', dialCode: '880'),
      ICountryWithCodeAndDial(countryName: 'BELGIUM', countryCode: 'be', dialCode: '32'),
      ICountryWithCodeAndDial(countryName: 'BURKINA FASO', countryCode: 'bf', dialCode: '226'),
      ICountryWithCodeAndDial(countryName: 'BULGARIA', countryCode: 'bg', dialCode: '359'),
      ICountryWithCodeAndDial(countryName: 'BAHRAIN', countryCode: 'bh', dialCode: '973'),
      ICountryWithCodeAndDial(countryName: 'BURUNDI', countryCode: 'bi', dialCode: '257'),
      ICountryWithCodeAndDial(countryName: 'BENIN', countryCode: 'bj', dialCode: '229'),
      ICountryWithCodeAndDial(countryName: 'SAINT BARTHELEMY', countryCode: 'bl', dialCode: '590'),
      ICountryWithCodeAndDial(countryName: 'BERMUDA', countryCode: 'bm', dialCode: '1441'),
      ICountryWithCodeAndDial(countryName: 'BRUNEI DARUSSALAM', countryCode: 'bn', dialCode: '673'),
      ICountryWithCodeAndDial(countryName: 'BOLIVIA', countryCode: 'bo', dialCode: '591'),
      ICountryWithCodeAndDial(countryName: 'BRAZIL', countryCode: 'br', dialCode: '55'),
      ICountryWithCodeAndDial(countryName: 'BAHAMAS', countryCode: 'bs', dialCode: '1242'),
      ICountryWithCodeAndDial(countryName: 'BHUTAN', countryCode: 'bt', dialCode: '975'),
      ICountryWithCodeAndDial(countryName: 'BOTSWANA', countryCode: 'bw', dialCode: '267'),
      ICountryWithCodeAndDial(countryName: 'BELARUS', countryCode: 'by', dialCode: '375'),
      ICountryWithCodeAndDial(countryName: 'BELIZE', countryCode: 'bz', dialCode: '501'),
      ICountryWithCodeAndDial(countryName: 'CANADA', countryCode: 'ca', dialCode: '1'),
      ICountryWithCodeAndDial(countryName: 'COCOS (KEELING) ISLANDS', countryCode: 'cc', dialCode: '61'),
      ICountryWithCodeAndDial(countryName: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', countryCode: 'cd', dialCode: '243'),
      ICountryWithCodeAndDial(countryName: 'CENTRAL AFRICAN REPUBLIC', countryCode: 'cf', dialCode: '236'),
      ICountryWithCodeAndDial(countryName: 'CONGO', countryCode: 'cg', dialCode: '242'),
      ICountryWithCodeAndDial(countryName: 'SWITZERLAND', countryCode: 'ch', dialCode: '41'),
      ICountryWithCodeAndDial(countryName: 'COTE D IVOIRE', countryCode: 'ci', dialCode: '225'),
      ICountryWithCodeAndDial(countryName: 'COOK ISLANDS', countryCode: 'ck', dialCode: '682'),
      ICountryWithCodeAndDial(countryName: 'CHILE', countryCode: 'cl', dialCode: '56'),
      ICountryWithCodeAndDial(countryName: 'CAMEROON', countryCode: 'cm', dialCode: '237'),
      ICountryWithCodeAndDial(countryName: 'CHINA', countryCode: 'cn', dialCode: '86'),
      ICountryWithCodeAndDial(countryName: 'COLOMBIA', countryCode: 'co', dialCode: '57'),
      ICountryWithCodeAndDial(countryName: 'COSTA RICA', countryCode: 'cr', dialCode: '506'),
      ICountryWithCodeAndDial(countryName: 'CUBA', countryCode: 'cu', dialCode: '53'),
      ICountryWithCodeAndDial(countryName: 'CAPE VERDE', countryCode: 'cv', dialCode: '238'),
      ICountryWithCodeAndDial(countryName: 'CHRISTMAS ISLAND', countryCode: 'cx', dialCode: '61'),
      ICountryWithCodeAndDial(countryName: 'CYPRUS', countryCode: 'cy', dialCode: '357'),
      ICountryWithCodeAndDial(countryName: 'CZECH REPUBLIC', countryCode: 'cz', dialCode: '420'),
      ICountryWithCodeAndDial(countryName: 'GERMANY', countryCode: 'de', dialCode: '49'),
      ICountryWithCodeAndDial(countryName: 'DJIBOUTI', countryCode: 'dj', dialCode: '253'),
      ICountryWithCodeAndDial(countryName: 'DENMARK', countryCode: 'dk', dialCode: '45'),
      ICountryWithCodeAndDial(countryName: 'DOMINICA', countryCode: 'dm', dialCode: '1767'),
      ICountryWithCodeAndDial(countryName: 'DOMINICAN REPUBLIC', countryCode: 'do', dialCode: '1809'),
      ICountryWithCodeAndDial(countryName: 'ALGERIA', countryCode: 'dz', dialCode: '213'),
      ICountryWithCodeAndDial(countryName: 'ECUADOR', countryCode: 'ec', dialCode: '593'),
      ICountryWithCodeAndDial(countryName: 'ESTONIA', countryCode: 'ee', dialCode: '372'),
      ICountryWithCodeAndDial(countryName: 'EGYPT', countryCode: 'eg', dialCode: '20'),
      ICountryWithCodeAndDial(countryName: 'ERITREA', countryCode: 'er', dialCode: '291'),
      ICountryWithCodeAndDial(countryName: 'SPAIN', countryCode: 'es', dialCode: '34'),
      ICountryWithCodeAndDial(countryName: 'ETHIOPIA', countryCode: 'et', dialCode: '251'),
      ICountryWithCodeAndDial(countryName: 'FINLAND', countryCode: 'fi', dialCode: '358'),
      ICountryWithCodeAndDial(countryName: 'FIJI', countryCode: 'fj', dialCode: '679'),
      ICountryWithCodeAndDial(countryName: 'FALKLAND ISLANDS (MALVINAS)', countryCode: 'fk', dialCode: '500'),
      ICountryWithCodeAndDial(countryName: 'MICRONESIA, FEDERATED STATES OF', countryCode: 'fm', dialCode: '691'),
      ICountryWithCodeAndDial(countryName: 'FAROE ISLANDS', countryCode: 'fo', dialCode: '298'),
      ICountryWithCodeAndDial(countryName: 'FRANCE', countryCode: 'fr', dialCode: '33'),
      ICountryWithCodeAndDial(countryName: 'GABON', countryCode: 'ga', dialCode: '241'),
      ICountryWithCodeAndDial(countryName: 'UNITED KINGDOM', countryCode: 'gb', dialCode: '44'),
      ICountryWithCodeAndDial(countryName: 'GRENADA', countryCode: 'gd', dialCode: '1473'),
      ICountryWithCodeAndDial(countryName: 'GEORGIA', countryCode: 'ge', dialCode: '995'),
      ICountryWithCodeAndDial(countryName: 'GHANA', countryCode: 'gh', dialCode: '233'),
      ICountryWithCodeAndDial(countryName: 'GIBRALTAR', countryCode: 'gi', dialCode: '350'),
      ICountryWithCodeAndDial(countryName: 'GREENLAND', countryCode: 'gl', dialCode: '299'),
      ICountryWithCodeAndDial(countryName: 'GAMBIA', countryCode: 'gm', dialCode: '220'),
      ICountryWithCodeAndDial(countryName: 'GUINEA', countryCode: 'gn', dialCode: '224'),
      ICountryWithCodeAndDial(countryName: 'EQUATORIAL GUINEA', countryCode: 'gq', dialCode: '240'),
      ICountryWithCodeAndDial(countryName: 'GREECE', countryCode: 'gr', dialCode: '30'),
      ICountryWithCodeAndDial(countryName: 'GUATEMALA', countryCode: 'gt', dialCode: '502'),
      ICountryWithCodeAndDial(countryName: 'GUAM', countryCode: 'gu', dialCode: '1671'),
      ICountryWithCodeAndDial(countryName: 'GUINEA-BISSAU', countryCode: 'gw', dialCode: '245'),
      ICountryWithCodeAndDial(countryName: 'GUYANA', countryCode: 'gy', dialCode: '592'),
      ICountryWithCodeAndDial(countryName: 'HONG KONG', countryCode: 'hk', dialCode: '852'),
      ICountryWithCodeAndDial(countryName: 'HONDURAS', countryCode: 'hn', dialCode: '504'),
      ICountryWithCodeAndDial(countryName: 'CROATIA', countryCode: 'hr', dialCode: '385'),
      ICountryWithCodeAndDial(countryName: 'HAITI', countryCode: 'ht', dialCode: '509'),
      ICountryWithCodeAndDial(countryName: 'HUNGARY', countryCode: 'hu', dialCode: '36'),
      ICountryWithCodeAndDial(countryName: 'INDONESIA', countryCode: 'id', dialCode: '62'),
      ICountryWithCodeAndDial(countryName: 'IRELAND', countryCode: 'ie', dialCode: '353'),
      ICountryWithCodeAndDial(countryName: 'ISRAEL', countryCode: 'il', dialCode: '972'),
      ICountryWithCodeAndDial(countryName: 'ISLE OF MAN', countryCode: 'im', dialCode: '44'),
      ICountryWithCodeAndDial(countryName: 'INDIA', countryCode: 'in', dialCode: '91'),
      ICountryWithCodeAndDial(countryName: 'IRAQ', countryCode: 'iq', dialCode: '964'),
      ICountryWithCodeAndDial(countryName: 'IRAN, ISLAMIC REPUBLIC OF', countryCode: 'ir', dialCode: '98'),
      ICountryWithCodeAndDial(countryName: 'ICELAND', countryCode: 'is', dialCode: '354'),
      ICountryWithCodeAndDial(countryName: 'ITALY', countryCode: 'it', dialCode: '39'),
      ICountryWithCodeAndDial(countryName: 'JAMAICA', countryCode: 'jm', dialCode: '1876'),
      ICountryWithCodeAndDial(countryName: 'JORDAN', countryCode: 'jo', dialCode: '962'),
      ICountryWithCodeAndDial(countryName: 'JAPAN', countryCode: 'jp', dialCode: '81'),
      ICountryWithCodeAndDial(countryName: 'KENYA', countryCode: 'ke', dialCode: '254'),
      ICountryWithCodeAndDial(countryName: 'KYRGYZSTAN', countryCode: 'kg', dialCode: '996'),
      ICountryWithCodeAndDial(countryName: 'CAMBODIA', countryCode: 'kh', dialCode: '855'),
      ICountryWithCodeAndDial(countryName: 'KIRIBATI', countryCode: 'ki', dialCode: '686'),
      ICountryWithCodeAndDial(countryName: 'COMOROS', countryCode: 'km', dialCode: '269'),
      ICountryWithCodeAndDial(countryName: 'SAINT KITTS AND NEVIS', countryCode: 'kn', dialCode: '1869'),
      ICountryWithCodeAndDial(countryName: 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF', countryCode: 'kp', dialCode: '850'),
      ICountryWithCodeAndDial(countryName: 'KOREA REPUBLIC OF', countryCode: 'kr', dialCode: '82'),
      ICountryWithCodeAndDial(countryName: 'KUWAIT', countryCode: 'kw', dialCode: '965'),
      ICountryWithCodeAndDial(countryName: 'CAYMAN ISLANDS', countryCode: 'ky', dialCode: '1345'),
      ICountryWithCodeAndDial(countryName: 'KAZAKSTAN', countryCode: 'kz', dialCode: '7'),
      ICountryWithCodeAndDial(countryName: 'LAO PEOPLES DEMOCRATIC REPUBLIC', countryCode: 'la', dialCode: '856'),
      ICountryWithCodeAndDial(countryName: 'LEBANON', countryCode: 'lb', dialCode: '961'),
      ICountryWithCodeAndDial(countryName: 'SAINT LUCIA', countryCode: 'lc', dialCode: '1758'),
      ICountryWithCodeAndDial(countryName: 'LIECHTENSTEIN', countryCode: 'li', dialCode: '423'),
      ICountryWithCodeAndDial(countryName: 'SRI LANKA', countryCode: 'lk', dialCode: '94'),
      ICountryWithCodeAndDial(countryName: 'LIBERIA', countryCode: 'lr', dialCode: '231'),
      ICountryWithCodeAndDial(countryName: 'LESOTHO', countryCode: 'ls', dialCode: '266'),
      ICountryWithCodeAndDial(countryName: 'LITHUANIA', countryCode: 'lt', dialCode: '370'),
      ICountryWithCodeAndDial(countryName: 'LUXEMBOURG', countryCode: 'lu', dialCode: '352'),
      ICountryWithCodeAndDial(countryName: 'LATVIA', countryCode: 'lv', dialCode: '371'),
      ICountryWithCodeAndDial(countryName: 'LIBYAN ARAB JAMAHIRIYA', countryCode: 'ly', dialCode: '218'),
      ICountryWithCodeAndDial(countryName: 'MOROCCO', countryCode: 'ma', dialCode: '212'),
      ICountryWithCodeAndDial(countryName: 'MONACO', countryCode: 'mc', dialCode: '377'),
      ICountryWithCodeAndDial(countryName: 'MOLDOVA, REPUBLIC OF', countryCode: 'md', dialCode: '373'),
      ICountryWithCodeAndDial(countryName: 'MONTENEGRO', countryCode: 'me', dialCode: '382'),
      ICountryWithCodeAndDial(countryName: 'SAINT MARTIN', countryCode: 'mf', dialCode: '1599'),
      ICountryWithCodeAndDial(countryName: 'MADAGASCAR', countryCode: 'mg', dialCode: '261'),
      ICountryWithCodeAndDial(countryName: 'MARSHALL ISLANDS', countryCode: 'mh', dialCode: '692'),
      ICountryWithCodeAndDial(countryName: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', countryCode: 'mk', dialCode: '389'),
      ICountryWithCodeAndDial(countryName: 'MALI', countryCode: 'ml', dialCode: '223'),
      ICountryWithCodeAndDial(countryName: 'MYANMAR', countryCode: 'mm', dialCode: '95'),
      ICountryWithCodeAndDial(countryName: 'MONGOLIA', countryCode: 'mn', dialCode: '976'),
      ICountryWithCodeAndDial(countryName: 'MACAU', countryCode: 'mo', dialCode: '853'),
      ICountryWithCodeAndDial(countryName: 'NORTHERN MARIANA ISLANDS', countryCode: 'mp', dialCode: '1670'),
      ICountryWithCodeAndDial(countryName: 'MAURITANIA', countryCode: 'mr', dialCode: '222'),
      ICountryWithCodeAndDial(countryName: 'MONTSERRAT', countryCode: 'ms', dialCode: '1664'),
      ICountryWithCodeAndDial(countryName: 'MALTA', countryCode: 'mt', dialCode: '356'),
      ICountryWithCodeAndDial(countryName: 'MAURITIUS', countryCode: 'mu', dialCode: '230'),
      ICountryWithCodeAndDial(countryName: 'MALDIVES', countryCode: 'mv', dialCode: '960'),
      ICountryWithCodeAndDial(countryName: 'MALAWI', countryCode: 'mw', dialCode: '265'),
      ICountryWithCodeAndDial(countryName: 'MEXICO', countryCode: 'mx', dialCode: '52'),
      ICountryWithCodeAndDial(countryName: 'MALAYSIA', countryCode: 'my', dialCode: '60'),
      ICountryWithCodeAndDial(countryName: 'MOZAMBIQUE', countryCode: 'mz', dialCode: '258'),
      ICountryWithCodeAndDial(countryName: 'NAMIBIA', countryCode: 'na', dialCode: '264'),
      ICountryWithCodeAndDial(countryName: 'NEW CALEDONIA', countryCode: 'nc', dialCode: '687'),
      ICountryWithCodeAndDial(countryName: 'NIGER', countryCode: 'ne', dialCode: '227'),
      ICountryWithCodeAndDial(countryName: 'NIGERIA', countryCode: 'ng', dialCode: '234'),
      ICountryWithCodeAndDial(countryName: 'NICARAGUA', countryCode: 'ni', dialCode: '505'),
      ICountryWithCodeAndDial(countryName: 'NETHERLANDS', countryCode: 'nl', dialCode: '31'),
      ICountryWithCodeAndDial(countryName: 'NORWAY', countryCode: 'no', dialCode: '47'),
      ICountryWithCodeAndDial(countryName: 'NEPAL', countryCode: 'np', dialCode: '977'),
      ICountryWithCodeAndDial(countryName: 'NAURU', countryCode: 'nr', dialCode: '674'),
      ICountryWithCodeAndDial(countryName: 'NIUE', countryCode: 'nu', dialCode: '683'),
      ICountryWithCodeAndDial(countryName: 'NEW ZEALAND', countryCode: 'nz', dialCode: '64'),
      ICountryWithCodeAndDial(countryName: 'OMAN', countryCode: 'om', dialCode: '968'),
      ICountryWithCodeAndDial(countryName: 'PANAMA', countryCode: 'pa', dialCode: '507'),
      ICountryWithCodeAndDial(countryName: 'PERU', countryCode: 'pe', dialCode: '51'),
      ICountryWithCodeAndDial(countryName: 'FRENCH POLYNESIA', countryCode: 'pf', dialCode: '689'),
      ICountryWithCodeAndDial(countryName: 'PAPUA NEW GUINEA', countryCode: 'pg', dialCode: '675'),
      ICountryWithCodeAndDial(countryName: 'PHILIPPINES', countryCode: 'ph', dialCode: '63'),
      ICountryWithCodeAndDial(countryName: 'PAKISTAN', countryCode: 'pk', dialCode: '92'),
      ICountryWithCodeAndDial(countryName: 'POLAND', countryCode: 'pl', dialCode: '48'),
      ICountryWithCodeAndDial(countryName: 'SAINT PIERRE AND MIQUELON', countryCode: 'pm', dialCode: '508'),
      ICountryWithCodeAndDial(countryName: 'PITCAIRN', countryCode: 'pn', dialCode: '870'),
      ICountryWithCodeAndDial(countryName: 'PUERTO RICO', countryCode: 'pr', dialCode: '1'),
      ICountryWithCodeAndDial(countryName: 'PORTUGAL', countryCode: 'pt', dialCode: '351'),
      ICountryWithCodeAndDial(countryName: 'PALAU', countryCode: 'pw', dialCode: '680'),
      ICountryWithCodeAndDial(countryName: 'PARAGUAY', countryCode: 'py', dialCode: '595'),
      ICountryWithCodeAndDial(countryName: 'QATAR', countryCode: 'qa', dialCode: '974'),
      ICountryWithCodeAndDial(countryName: 'ROMANIA', countryCode: 'ro', dialCode: '40'),
      ICountryWithCodeAndDial(countryName: 'SERBIA', countryCode: 'rs', dialCode: '381'),
      ICountryWithCodeAndDial(countryName: 'RUSSIAN FEDERATION', countryCode: 'ru', dialCode: '7'),
      ICountryWithCodeAndDial(countryName: 'RWANDA', countryCode: 'rw', dialCode: '250'),
      ICountryWithCodeAndDial(countryName: 'SAUDI ARABIA', countryCode: 'sa', dialCode: '966'),
      ICountryWithCodeAndDial(countryName: 'SOLOMON ISLANDS', countryCode: 'sb', dialCode: '677'),
      ICountryWithCodeAndDial(countryName: 'SEYCHELLES', countryCode: 'sc', dialCode: '248'),
      ICountryWithCodeAndDial(countryName: 'SUDAN', countryCode: 'sd', dialCode: '249'),
      ICountryWithCodeAndDial(countryName: 'SWEDEN', countryCode: 'se', dialCode: '46'),
      ICountryWithCodeAndDial(countryName: 'SINGAPORE', countryCode: 'sg', dialCode: '65'),
      ICountryWithCodeAndDial(countryName: 'SAINT HELENA', countryCode: 'sh', dialCode: '290'),
      ICountryWithCodeAndDial(countryName: 'SLOVENIA', countryCode: 'si', dialCode: '386'),
      ICountryWithCodeAndDial(countryName: 'SLOVAKIA', countryCode: 'sk', dialCode: '421'),
      ICountryWithCodeAndDial(countryName: 'SIERRA LEONE', countryCode: 'sl', dialCode: '232'),
      ICountryWithCodeAndDial(countryName: 'SAN MARINO', countryCode: 'sm', dialCode: '378'),
      ICountryWithCodeAndDial(countryName: 'SENEGAL', countryCode: 'sn', dialCode: '221'),
      ICountryWithCodeAndDial(countryName: 'SOMALIA', countryCode: 'so', dialCode: '252'),
      ICountryWithCodeAndDial(countryName: 'SURINAME', countryCode: 'sr', dialCode: '597'),
      ICountryWithCodeAndDial(countryName: 'SAO TOME AND PRINCIPE', countryCode: 'st', dialCode: '239'),
      ICountryWithCodeAndDial(countryName: 'EL SALVADOR', countryCode: 'sv', dialCode: '503'),
      ICountryWithCodeAndDial(countryName: 'SYRIAN ARAB REPUBLIC', countryCode: 'sy', dialCode: '963'),
      ICountryWithCodeAndDial(countryName: 'SWAZILAND', countryCode: 'sz', dialCode: '268'),
      ICountryWithCodeAndDial(countryName: 'TURKS AND CAICOS ISLANDS', countryCode: 'tc', dialCode: '1649'),
      ICountryWithCodeAndDial(countryName: 'CHAD', countryCode: 'td', dialCode: '235'),
      ICountryWithCodeAndDial(countryName: 'TOGO', countryCode: 'tg', dialCode: '228'),
      ICountryWithCodeAndDial(countryName: 'THAILAND', countryCode: 'th', dialCode: '66'),
      ICountryWithCodeAndDial(countryName: 'TAJIKISTAN', countryCode: 'tj', dialCode: '992'),
      ICountryWithCodeAndDial(countryName: 'TOKELAU', countryCode: 'tk', dialCode: '690'),
      ICountryWithCodeAndDial(countryName: 'TIMOR-LESTE', countryCode: 'tl', dialCode: '670'),
      ICountryWithCodeAndDial(countryName: 'TURKMENISTAN', countryCode: 'tm', dialCode: '993'),
      ICountryWithCodeAndDial(countryName: 'TUNISIA', countryCode: 'tn', dialCode: '216'),
      ICountryWithCodeAndDial(countryName: 'TONGA', countryCode: 'to', dialCode: '676'),
      ICountryWithCodeAndDial(countryName: 'TURKEY', countryCode: 'tr', dialCode: '90'),
      ICountryWithCodeAndDial(countryName: 'TRINIDAD AND TOBAGO', countryCode: 'tt', dialCode: '1868'),
      ICountryWithCodeAndDial(countryName: 'TUVALU', countryCode: 'tv', dialCode: '688'),
      ICountryWithCodeAndDial(countryName: 'TAIWAN, PROVINCE OF CHINA', countryCode: 'tw', dialCode: '886'),
      ICountryWithCodeAndDial(countryName: 'TANZANIA, UNITED REPUBLIC OF', countryCode: 'tz', dialCode: '255'),
      ICountryWithCodeAndDial(countryName: 'UKRAINE', countryCode: 'ua', dialCode: '380'),
      ICountryWithCodeAndDial(countryName: 'UGANDA', countryCode: 'ug', dialCode: '256'),
      ICountryWithCodeAndDial(countryName: 'UNITED STATES', countryCode: 'us', dialCode: '1'),
      ICountryWithCodeAndDial(countryName: 'URUGUAY', countryCode: 'uy', dialCode: '598'),
      ICountryWithCodeAndDial(countryName: 'UZBEKISTAN', countryCode: 'uz', dialCode: '998'),
      ICountryWithCodeAndDial(countryName: 'HOLY SEE (VATICAN CITY STATE)', countryCode: 'va', dialCode: '39'),
      ICountryWithCodeAndDial(countryName: 'SAINT VINCENT AND THE GRENADINES', countryCode: 'vc', dialCode: '1784'),
      ICountryWithCodeAndDial(countryName: 'VENEZUELA', countryCode: 've', dialCode: '58'),
      ICountryWithCodeAndDial(countryName: 'VIRGIN ISLANDS, BRITISH', countryCode: 'vg', dialCode: '1284'),
      ICountryWithCodeAndDial(countryName: 'VIRGIN ISLANDS, U.S.', countryCode: 'vi', dialCode: '1340'),
      ICountryWithCodeAndDial(countryName: 'VIET NAM', countryCode: 'vn', dialCode: '84'),
      ICountryWithCodeAndDial(countryName: 'VANUATU', countryCode: 'vu', dialCode: '678'),
      ICountryWithCodeAndDial(countryName: 'WALLIS AND FUTUNA', countryCode: 'wf', dialCode: '681'),
      ICountryWithCodeAndDial(countryName: 'SAMOA', countryCode: 'ws', dialCode: '685'),
      ICountryWithCodeAndDial(countryName: 'KOSOVO', countryCode: 'xk', dialCode: '381'),
      ICountryWithCodeAndDial(countryName: 'YEMEN', countryCode: 'ye', dialCode: '967'),
      ICountryWithCodeAndDial(countryName: 'MAYOTTE', countryCode: 'yt', dialCode: '262'),
      ICountryWithCodeAndDial(countryName: 'SOUTH AFRICA', countryCode: 'za', dialCode: '27'),
      ICountryWithCodeAndDial(countryName: 'ZAMBIA', countryCode: 'zm', dialCode: '260'),
      ICountryWithCodeAndDial(countryName: 'ZIMBABWE', countryCode: 'zw', dialCode: '263 ')
    ];
  }
}
